### PR TITLE
codingGameService: Use CodnigGameService.AppIntegrationController

### PR DESCRIPTION
**Pull request by smspillaz**
https://phabricator.endlessm.com/T13630

### CODE REVIEW

**Comment by erikos** [comment]
We should use event_occurred, right? 

diff --git a/js/ui/components/codingGameService.js b/js/ui/components/codingGameService.js
index 88af9a4..6e7f8bc 100644
--- a/js/ui/components/codingGameService.js
+++ b/js/ui/components/codingGameService.js
@@ -73,7 +73,7 @@ const CodingChatboxTextService = new Lang.Class({
     _waitForNextWindowMove: function() {
         let wmCallback = Lang.bind(this, function(display, screen, window, op) {
             if (window && op == Meta.GrabOp.MOVING) {
-                this._service.call_external_event('move-window', null, null);
+                this._controller.event_occurred("move-window");
                 this._disconnectHandlersFor('move-window');
             }
         });
@@ -93,7 +93,7 @@ const CodingChatboxTextService = new Lang.Class({
 
         let timeoutCb = Lang.bind(this, function() {
             this._disconnectHandlersFor('stop-moving-windows');
-            this._service.call_external_event('stop-moving-windows', null, null);
+            this._controller.event_occurred("stop-move-window");
             return false;
         });

**Comment by erikos** [comment]
```
diff --git a/js/ui/components/codingGameService.js b/js/ui/components/codingGameService.js
index 88af9a4..6e7f8bc 100644
--- a/js/ui/components/codingGameService.js
+++ b/js/ui/components/codingGameService.js
@@ -73,7 +73,7 @@ const CodingChatboxTextService = new Lang.Class({
     _waitForNextWindowMove: function() {
         let wmCallback = Lang.bind(this, function(display, screen, window, op) {
             if (window && op == Meta.GrabOp.MOVING) {
-                this._service.call_external_event('move-window', null, null);
+                this._controller.event_occurred("move-window");
                 this._disconnectHandlersFor('move-window');
             }
         });
@@ -93,7 +93,7 @@ const CodingChatboxTextService = new Lang.Class({
 
         let timeoutCb = Lang.bind(this, function() {
             this._disconnectHandlersFor('stop-moving-windows');
-            this._service.call_external_event('stop-moving-windows', null, null);
+            this._controller.event_occurred("stop-move-window");
             return false;
         });

```

**Comment by erikos** [comment]
codingGameService: Use CodnigGameService.AppIntegrationController 

s/Codnig/Coding

**Comment by smspillaz** [comment]
Thanks for the review!

> We should use event_occurred

Yes, good point, I forgot about that API.

> codingGameService: Use CodnigGameService.AppIntegrationController

Thanks, will rebase and fix

**Pull request merged**
