### PR TITLE
debian: Add dependency on libwobbly

### PR DESCRIPTION
**Pull request by smspillaz**
https://phabricator.endlessm.com/T1790

### CODE REVIEW

**Comment by sgnn7** [comment]
@smspillaz I think you tagged the wrong issue here

**Comment by smspillaz** [comment]
@sgnn7 Ah, thanks. Its meant to be 1790.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by cosimoc** [comment]
I think you need to back out the `gvc` submodule change.
Also, we get the debian version automatically set in Jenkins, and you should not update the changelog manually.

**Comment by smspillaz** [comment]
> I think you need to back out the gvc submodule change.

Ah yikes, that keeps sneaking in. Thanks for catching that.

**Comment by smspillaz** [comment]
Done.

**Pull request merged**
