### PR TITLE
DiscoveryFeed: make the window semi-transparent

### PR DESCRIPTION
**Pull request by erikos**
This should have the same values as the search
result widget.

### CODE REVIEW

**Comment by smspillaz** [comment]
Hmm, my preference here would be to set an actual transparency hint on the GtkWindow itself. I believe that we're doing that within the app itself, though it doesn't seem to be working :/

**Review by cosimoc — CHANGES_REQUESTED** [review]
I agree, this should not be done at the window manager level but within the app.
I believe the old app store did that, so we may be able to take inspiration from that app for what we need to do here.

**Comment by erikos** [comment]
Right, setting the opacity on the window itself in the app was the first thing I tried and we actually had already a setting there but it is not picked up. The window is composited like noted in the doc to be needed. I did try to set the opacity for a gtkwindow as well in a test case but it does not seem to be picked up.

As we do set opacity to full when done with window mapping in the windowManager.js I special cased those to not be set in the DiscoveryFeed case to make sure we do not override opacity but same result, that setting is not propagated it looks like.

Looked at the apps-store code but could not find a special casing there yet regarding opacity.

**Comment by cosimoc** [comment]
@erikos Not sure if setting the opacity on the window itself is the way to go, but I believe you can tweak the background color of the main GtkWindow using CSS.

**Comment by cosimoc** [comment]
(And just to confirm, the opacity that you would set from GTK is never going to be reflected in the opacity values you see in `windowManager.js` -- they're unrelated.)

**Comment by erikos** [comment]
Thanks Cosimo for your comments - new approach inspired by eos-app-store https://github.com/endlessm/eos-discovery-feed/pull/31

**Pull request closed without merging**
